version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_API_URL: ${REACT_APP_BASE_API_URL}
    ports:
      - "8080:8080"
    depends_on:
      - backend

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    restart: always
#
#  client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    volumes:
#      - ./client/config/config.yaml:/app/config/config.yaml # 注意，一定要提前生成config
#    restart: always