version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BASE_API_URL: http://localhost:8000 # 注意：这里可换成 nginx 代理地址
    ports:
      - '80:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/config.yaml:/app/config/config.yaml # 注意，一定要提前生成config
    restart: always
